<?php

// $_SERVER['APP_ENVIRONMENT'] = 'staging';

// $_SERVER['ENVIRONMENT_MYSQL_HOST_MASTER'] = 'storm_main_mysql';
// $_SERVER['ENVIRONMENT_MYSQL_PORT_MASTER'] = '3306';

// $_SERVER['ENVIRONMENT_MYSQL_HOST_READ'] = 'storm_main_mysql';
// $_SERVER['ENVIRONMENT_MYSQL_PORT_READ'] = '3306';

// $_SERVER['ENVIRONMENT_MYSQL_USER'] = 'root';
// $_SERVER['ENVIRONMENT_MYSQL_PWRD'] = 'root';

// $_SERVER['ENVIRONMENT_REDIS_HOST'] = 'storm_main_redis';
// $_SERVER['ENVIRONMENT_REDIS_PORT'] = '6379';

// $_SERVER['ENVIRONMENT_STORM_OAUTH2_HOST'] = 'storm_api_oauth2';
// $_SERVER['ENVIRONMENT_STORM_OAUTH2_PORT'] = '5000';

// $_SERVER['ENVIRONMENT_STORM_WALLET_HOST'] = 'storm_api_wallet';
// $_SERVER['ENVIRONMENT_STORM_WALLET_PORT'] = '5001';

// $_SERVER['ENVIRONMENT_DOMAIN_KUDOS'] = '.storm.tech';

// $_SERVER['ENVIRONMENT_SUBDOMAIN_KUDOS_ADMIN'] = 'kudos-admin-stg';
// $_SERVER['ENVIRONMENT_SUBDOMAIN_KUDOS_API'] = 'kudos-api-stg';
// $_SERVER['ENVIRONMENT_SUBDOMAIN_KUDOS_CLIENT'] = 'kudos-stg';
// $_SERVER['ENVIRONMENT_SUBDOMAIN_KUDOS_CLIENT_ASSETS'] = 'mydeals-stg';

// $_SERVER['ENVIRONMENT_CONTAINER_NAME_KUDOS_ADMIN'] = 'staging_kudos-admin_1';
// $_SERVER['ENVIRONMENT_CONTAINER_NAME_KUDOS_API'] = 'staging_kudos-api_1';
// $_SERVER['ENVIRONMENT_CONTAINER_NAME_KUDOS_CLIENT'] = 'staging_kudos-client_1';

// $_SERVER['ENVIRONMENT_CONTAINER_PORT_KUDOS_ADMIN'] = '9000';
// $_SERVER['ENVIRONMENT_CONTAINER_PORT_KUDOS_API'] = '9000';
// $_SERVER['ENVIRONMENT_CONTAINER_PORT_KUDOS_CLIENT'] = '9000';

